# Copyright (C) 2026 Ailin One, Inc.
#
# This file is part of Collective Intelligence Engine (ci).
# Licensed under the GNU Affero General Public License v3.0 or later.
# See LICENSE in the repository root, or <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later
# Source: https://github.com/ailinone/collective-intelligence

apis:
  yaml:
    root: ./openapi-spec.yaml
  json:
    root: ./openapi-spec.json

extends:
  - recommended

rules:
  operation-operationId: error
  operation-operationId-unique: error
  operation-2xx-response: error
  security-defined: error
