// Copyright (C) 2026 Ailin One, Inc.
//
// This file is part of Collective Intelligence Engine (ci).
// Licensed under the GNU Affero General Public License v3.0 or later.
// See LICENSE in the repository root, or <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
// Source: https://github.com/ailinone/collective-intelligence

import 'dotenv/config';
import bcrypt from 'bcrypt';
import { PrismaClient, Prisma } from '@/generated/prisma/index.js';
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';
import { logger } from '@/utils/logger';
import { syncDefaultRoles } from '@/services/rbac-sync-service';
import { serializeError } from '@/utils/type-guards';
import { computeModelUid } from '@/database/model-uid';

const DEFAULT_OWNER_EMAIL = 'founder@ailin.dev';
const DEFAULT_OWNER_NAME = 'Ailin Founder';
const DEFAULT_OWNER_PASSWORD = 'ChangeMeNow!123';

const SEEDED_ORGANIZATION_ID = '00000000-0000-0000-0000-000000000001';

export async function seedDatabase(): Promise<void> {
  // Prisma 7 requires adapter for database connection
  const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
  const adapter = new PrismaPg(pool);
  const prisma = new PrismaClient({ adapter });

  try {
    await syncDefaultRoles();

    const organization = await prisma.organization.upsert({
      where: { id: SEEDED_ORGANIZATION_ID },
      update: {
        tier: 'enterprise',
        status: 'active',
      },
      create: {
        id: SEEDED_ORGANIZATION_ID,
        name: 'Ailin Dev',
        tier: 'enterprise',
        status: 'active',
      },
    });

    const ownerRole = await prisma.role.findUnique({
      where: { name: 'owner' },
    });

    if (!ownerRole) {
      throw new Error('Owner role not found. Ensure default RBAC roles are created.');
    }

    const ownerPasswordPlain =
      process.env.SEED_OWNER_PASSWORD && process.env.SEED_OWNER_PASSWORD.trim().length > 0
        ? process.env.SEED_OWNER_PASSWORD
        : DEFAULT_OWNER_PASSWORD;

    if (!process.env.SEED_OWNER_PASSWORD) {
      logger.warn(
        { defaultPassword: DEFAULT_OWNER_PASSWORD },
        'SEED_OWNER_PASSWORD not provided. Using default password for seeded owner user. Update immediately in production environments.'
      );
    }

    const passwordHash = await bcrypt.hash(ownerPasswordPlain, 12);

    const ownerUser = await prisma.user.upsert({
      where: { email: DEFAULT_OWNER_EMAIL },
      update: {
        name: DEFAULT_OWNER_NAME,
        organizationId: organization.id,
        role: ownerRole.name,
        status: 'active',
        passwordHash,
      },
      create: {
        email: DEFAULT_OWNER_EMAIL,
        name: DEFAULT_OWNER_NAME,
        organizationId: organization.id,
        role: ownerRole.name,
        status: 'active',
        passwordHash,
      },
    });

    await prisma.userRole.upsert({
      where: {
        userId_organizationId_roleId: {
          userId: ownerUser.id,
          organizationId: organization.id,
          roleId: ownerRole.id,
        },
      },
      update: {},
      create: {
        userId: ownerUser.id,
        organizationId: organization.id,
        roleId: ownerRole.id,
      },
    });

    const providersToSeed = [
      {
        id: 'openai',
        name: 'openai',
        displayName: 'OpenAI',
      },
      {
        id: 'anthropic',
        name: 'anthropic',
        displayName: 'Anthropic',
      },
      {
        id: 'google',
        name: 'google',
        displayName: 'Google DeepMind',
      },
    ];

    for (const provider of providersToSeed) {
      await prisma.provider.upsert({
        where: { id: provider.id },
        update: {
          name: provider.name,
          displayName: provider.displayName,
          status: 'active',
          health: {
            status: 'healthy',
            lastSync: new Date().toISOString(),
            source: 'seed',
          },
        },
        create: {
          id: provider.id,
          name: provider.name,
          displayName: provider.displayName,
          status: 'active',
          health: {
            status: 'healthy',
            lastSync: new Date().toISOString(),
            source: 'seed',
          },
        },
      });
    }

    const modelsToSeed: Array<{
      id: string;
      providerId: string;
      name: string;
      displayName: string;
      contextWindow: number;
      maxOutputTokens: number;
      inputCostPer1k: string;
      outputCostPer1k: string;
      capabilities: string[];
      performance: Record<string, unknown>;
    }> = [
      // GPT-5.x Family - Latest generation models
      {
        id: 'openai:gpt-5.1',
        providerId: 'openai',
        name: 'gpt-5.1',
        displayName: 'GPT-5.1',
        contextWindow: 400000,
        maxOutputTokens: 128000,
        inputCostPer1k: '1.25',
        outputCostPer1k: '10.0',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'reasoning',
          'agents',
          'multimodal',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 950,
          throughput: 120,
          quality: 0.985,
          reliability: 0.995,
        },
      },
      {
        id: 'openai:gpt-5.1-codex',
        providerId: 'openai',
        name: 'gpt-5.1-codex',
        displayName: 'GPT-5.1 Codex',
        contextWindow: 400000,
        maxOutputTokens: 128000,
        inputCostPer1k: '1.25',
        outputCostPer1k: '10.0',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'reasoning',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 900,
          throughput: 130,
          quality: 0.98,
          reliability: 0.994,
        },
      },
      {
        id: 'openai:gpt-5-codex',
        providerId: 'openai',
        name: 'gpt-5-codex',
        displayName: 'GPT-5 Codex',
        contextWindow: 400000,
        maxOutputTokens: 128000,
        inputCostPer1k: '1.25',
        outputCostPer1k: '10.0',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'reasoning',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 1000,
          throughput: 125,
          quality: 0.975,
          reliability: 0.993,
        },
      },
      {
        id: 'openai:gpt-5-pro',
        providerId: 'openai',
        name: 'gpt-5-pro',
        displayName: 'GPT-5 Pro',
        contextWindow: 512000,
        maxOutputTokens: 256000,
        inputCostPer1k: '15.0',
        outputCostPer1k: '120.0',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'reasoning',
          'agents',
          'multimodal',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
          'deep_research',
        ],
        performance: {
          latencyMs: 1200,
          throughput: 80,
          quality: 0.995,
          reliability: 0.997,
        },
      },
      {
        id: 'openai:gpt-5.1-codex-mini',
        providerId: 'openai',
        name: 'gpt-5.1-codex-mini',
        displayName: 'GPT-5.1 Codex Mini',
        contextWindow: 200000,
        maxOutputTokens: 64000,
        inputCostPer1k: '0.25',
        outputCostPer1k: '2.0',
        capabilities: [
          'chat',
          'function_calling',
          'streaming',
          'json_mode',
          'reasoning',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 600,
          throughput: 250,
          quality: 0.93,
          reliability: 0.99,
        },
      },
      {
        id: 'openai:codex-mini-latest',
        providerId: 'openai',
        name: 'codex-mini-latest',
        displayName: 'Codex Mini Latest',
        contextWindow: 64000,
        maxOutputTokens: 16384,
        inputCostPer1k: '1.5',
        outputCostPer1k: '6.0',
        capabilities: [
          'chat',
          'function_calling',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 450,
          throughput: 300,
          quality: 0.88,
          reliability: 0.96,
        },
      },
      {
        id: 'openai:gpt-5-search-api',
        providerId: 'openai',
        name: 'gpt-5-search-api',
        displayName: 'GPT-5 Search API',
        contextWindow: 128000,
        maxOutputTokens: 32768,
        inputCostPer1k: '1.25',
        outputCostPer1k: '10.0',
        capabilities: [
          'chat',
          'function_calling',
          'streaming',
          'json_mode',
          'reasoning',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 1000,
          throughput: 110,
          quality: 0.98,
          reliability: 0.994,
        },
      },

      // GPT-4o / Realtime / Audio Family
      {
        id: 'openai:gpt-4o',
        providerId: 'openai',
        name: 'gpt-4o',
        displayName: 'GPT-4o',
        contextWindow: 128000,
        maxOutputTokens: 16384,
        inputCostPer1k: '2.5',
        outputCostPer1k: '10.0',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 2000,
          throughput: 100,
          quality: 0.95,
          reliability: 0.99,
        },
      },
      {
        id: 'openai:gpt-4o-2024-05-13',
        providerId: 'openai',
        name: 'gpt-4o-2024-05-13',
        displayName: 'GPT-4o (2024-05-13)',
        contextWindow: 128000,
        maxOutputTokens: 16384,
        inputCostPer1k: '5.0',
        outputCostPer1k: '15.0',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 2100,
          throughput: 95,
          quality: 0.945,
          reliability: 0.985,
        },
      },
      {
        id: 'openai:gpt-4o-mini',
        providerId: 'openai',
        name: 'gpt-4o-mini',
        displayName: 'GPT-4o Mini',
        contextWindow: 128000,
        maxOutputTokens: 16384,
        inputCostPer1k: '0.15',
        outputCostPer1k: '0.6',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 1500,
          throughput: 120,
          quality: 0.9,
          reliability: 0.99,
        },
      },
      {
        id: 'openai:gpt-realtime',
        providerId: 'openai',
        name: 'gpt-realtime',
        displayName: 'GPT Realtime',
        contextWindow: 128000,
        maxOutputTokens: 32768,
        inputCostPer1k: '4.0',
        outputCostPer1k: '16.0',
        capabilities: [
          'chat',
          'function_calling',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
          'realtime_audio',
        ],
        performance: {
          latencyMs: 200,
          throughput: 500,
          quality: 0.94,
          reliability: 0.98,
        },
      },
      {
        id: 'openai:gpt-realtime-mini',
        providerId: 'openai',
        name: 'gpt-realtime-mini',
        displayName: 'GPT Realtime Mini',
        contextWindow: 64000,
        maxOutputTokens: 16384,
        inputCostPer1k: '0.6',
        outputCostPer1k: '2.4',
        capabilities: [
          'chat',
          'function_calling',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
          'realtime_audio',
        ],
        performance: {
          latencyMs: 150,
          throughput: 800,
          quality: 0.89,
          reliability: 0.97,
        },
      },
      {
        id: 'openai:gpt-4o-realtime-preview',
        providerId: 'openai',
        name: 'gpt-4o-realtime-preview',
        displayName: 'GPT-4o Realtime Preview',
        contextWindow: 128000,
        maxOutputTokens: 16384,
        inputCostPer1k: '5.0',
        outputCostPer1k: '20.0',
        capabilities: [
          'chat',
          'function_calling',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'code_interpreter',
          'mcp',
          'realtime_audio',
        ],
        performance: {
          latencyMs: 180,
          throughput: 600,
          quality: 0.93,
          reliability: 0.97,
        },
      },
      {
        id: 'openai:gpt-4o-mini-realtime-preview',
        providerId: 'openai',
        name: 'gpt-4o-mini-realtime-preview',
        displayName: 'GPT-4o Mini Realtime Preview',
        contextWindow: 64000,
        maxOutputTokens: 16384,
        inputCostPer1k: '0.6',
        outputCostPer1k: '2.4',
        capabilities: [
          'chat',
          'function_calling',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'code_interpreter',
          'mcp',
          'realtime_audio',
        ],
        performance: {
          latencyMs: 120,
          throughput: 1000,
          quality: 0.87,
          reliability: 0.96,
        },
      },
      {
        id: 'openai:gpt-audio',
        providerId: 'openai',
        name: 'gpt-audio',
        displayName: 'GPT Audio',
        contextWindow: 128000,
        maxOutputTokens: 16384,
        inputCostPer1k: '2.5',
        outputCostPer1k: '10.0',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
          'tts',
          'speech_to_text',
        ],
        performance: {
          latencyMs: 1800,
          throughput: 110,
          quality: 0.945,
          reliability: 0.985,
        },
      },
      {
        id: 'openai:gpt-audio-mini',
        providerId: 'openai',
        name: 'gpt-audio-mini',
        displayName: 'GPT Audio Mini',
        contextWindow: 64000,
        maxOutputTokens: 16384,
        inputCostPer1k: '0.6',
        outputCostPer1k: '2.4',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
          'tts',
          'speech_to_text',
        ],
        performance: {
          latencyMs: 1200,
          throughput: 150,
          quality: 0.88,
          reliability: 0.97,
        },
      },
      {
        id: 'openai:gpt-4o-audio-preview',
        providerId: 'openai',
        name: 'gpt-4o-audio-preview',
        displayName: 'GPT-4o Audio Preview',
        contextWindow: 128000,
        maxOutputTokens: 16384,
        inputCostPer1k: '2.5',
        outputCostPer1k: '10.0',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
          'tts',
          'speech_to_text',
        ],
        performance: {
          latencyMs: 1700,
          throughput: 120,
          quality: 0.94,
          reliability: 0.98,
        },
      },
      {
        id: 'openai:gpt-4o-mini-audio-preview',
        providerId: 'openai',
        name: 'gpt-4o-mini-audio-preview',
        displayName: 'GPT-4o Mini Audio Preview',
        contextWindow: 64000,
        maxOutputTokens: 16384,
        inputCostPer1k: '0.15',
        outputCostPer1k: '0.6',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'image_generation',
          'code_interpreter',
          'mcp',
          'tts',
          'speech_to_text',
        ],
        performance: {
          latencyMs: 1100,
          throughput: 160,
          quality: 0.86,
          reliability: 0.96,
        },
      },
      {
        id: 'openai:gpt-4o-search-preview',
        providerId: 'openai',
        name: 'gpt-4o-search-preview',
        displayName: 'GPT-4o Search Preview',
        contextWindow: 128000,
        maxOutputTokens: 16384,
        inputCostPer1k: '2.5',
        outputCostPer1k: '10.0',
        capabilities: [
          'chat',
          'function_calling',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 1500,
          throughput: 105,
          quality: 0.935,
          reliability: 0.985,
        },
      },
      {
        id: 'openai:gpt-4o-mini-search-preview',
        providerId: 'openai',
        name: 'gpt-4o-mini-search-preview',
        displayName: 'GPT-4o Mini Search Preview',
        contextWindow: 128000,
        maxOutputTokens: 16384,
        inputCostPer1k: '0.15',
        outputCostPer1k: '0.6',
        capabilities: [
          'chat',
          'function_calling',
          'streaming',
          'json_mode',
          'web_search',
          'file_search',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 1200,
          throughput: 140,
          quality: 0.885,
          reliability: 0.98,
        },
      },

      // o-series Family (reasoning models)
      {
        id: 'openai:o1',
        providerId: 'openai',
        name: 'o1',
        displayName: 'O1',
        contextWindow: 128000,
        maxOutputTokens: 32768,
        inputCostPer1k: '15.0',
        outputCostPer1k: '60.0',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'reasoning',
          'web_search',
          'file_search',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 4000,
          throughput: 50,
          quality: 0.975,
          reliability: 0.99,
        },
      },
      {
        id: 'openai:o1-mini',
        providerId: 'openai',
        name: 'o1-mini',
        displayName: 'O1 Mini',
        contextWindow: 128000,
        maxOutputTokens: 32768,
        inputCostPer1k: '1.1',
        outputCostPer1k: '4.4',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'reasoning',
          'web_search',
          'file_search',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 2500,
          throughput: 80,
          quality: 0.94,
          reliability: 0.98,
        },
      },
      {
        id: 'openai:o3',
        providerId: 'openai',
        name: 'o3',
        displayName: 'O3',
        contextWindow: 200000,
        maxOutputTokens: 100000,
        inputCostPer1k: '2.0',
        outputCostPer1k: '8.0',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'reasoning',
          'web_search',
          'file_search',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 3500,
          throughput: 60,
          quality: 0.985,
          reliability: 0.995,
        },
      },
      {
        id: 'openai:o3-pro',
        providerId: 'openai',
        name: 'o3-pro',
        displayName: 'O3 Pro',
        contextWindow: 200000,
        maxOutputTokens: 100000,
        inputCostPer1k: '20.0',
        outputCostPer1k: '80.0',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'reasoning',
          'web_search',
          'file_search',
          'code_interpreter',
          'mcp',
          'deep_research',
        ],
        performance: {
          latencyMs: 5000,
          throughput: 40,
          quality: 0.995,
          reliability: 0.997,
        },
      },
      {
        id: 'openai:o3-deep-research',
        providerId: 'openai',
        name: 'o3-deep-research',
        displayName: 'O3 Deep Research',
        contextWindow: 200000,
        maxOutputTokens: 100000,
        inputCostPer1k: '10.0',
        outputCostPer1k: '40.0',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'reasoning',
          'web_search',
          'file_search',
          'code_interpreter',
          'mcp',
          'deep_research',
        ],
        performance: {
          latencyMs: 6000,
          throughput: 35,
          quality: 0.997,
          reliability: 0.998,
        },
      },
      {
        id: 'openai:o4-mini',
        providerId: 'openai',
        name: 'o4-mini',
        displayName: 'O4 Mini',
        contextWindow: 128000,
        maxOutputTokens: 32768,
        inputCostPer1k: '1.1',
        outputCostPer1k: '4.4',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'reasoning',
          'web_search',
          'file_search',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 2000,
          throughput: 90,
          quality: 0.96,
          reliability: 0.99,
        },
      },
      {
        id: 'openai:o3-mini',
        providerId: 'openai',
        name: 'o3-mini',
        displayName: 'O3 Mini',
        contextWindow: 128000,
        maxOutputTokens: 32768,
        inputCostPer1k: '1.1',
        outputCostPer1k: '4.4',
        capabilities: [
          'chat',
          'function_calling',
          'vision',
          'streaming',
          'json_mode',
          'reasoning',
          'web_search',
          'file_search',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 1800,
          throughput: 100,
          quality: 0.95,
          reliability: 0.99,
        },
      },

      // Special Models
      {
        id: 'openai:computer-use-preview',
        providerId: 'openai',
        name: 'computer-use-preview',
        displayName: 'Computer Use Preview',
        contextWindow: 128000,
        maxOutputTokens: 16384,
        inputCostPer1k: '3.0',
        outputCostPer1k: '12.0',
        capabilities: [
          'chat',
          'function_calling',
          'streaming',
          'json_mode',
          'computer_use',
          'web_search',
          'file_search',
          'code_interpreter',
          'mcp',
        ],
        performance: {
          latencyMs: 2500,
          throughput: 85,
          quality: 0.93,
          reliability: 0.97,
        },
      },
      {
        id: 'openai:gpt-image-1',
        providerId: 'openai',
        name: 'gpt-image-1',
        displayName: 'GPT Image 1',
        contextWindow: 0,
        maxOutputTokens: 0,
        inputCostPer1k: '5.0',
        outputCostPer1k: '0',
        capabilities: ['image_generation'],
        performance: {
          latencyMs: 3000,
          throughput: 50,
          quality: 0.95,
          reliability: 0.98,
        },
      },
      {
        id: 'openai:gpt-image-1-mini',
        providerId: 'openai',
        name: 'gpt-image-1-mini',
        displayName: 'GPT Image 1 Mini',
        contextWindow: 0,
        maxOutputTokens: 0,
        inputCostPer1k: '2.0',
        outputCostPer1k: '0',
        capabilities: ['image_generation'],
        performance: {
          latencyMs: 2000,
          throughput: 80,
          quality: 0.88,
          reliability: 0.97,
        },
      },

      // Audio/TTS/Transcription Models
      {
        id: 'openai:gpt-4o-mini-tts',
        providerId: 'openai',
        name: 'gpt-4o-mini-tts',
        displayName: 'GPT-4o Mini TTS',
        contextWindow: 2000,
        maxOutputTokens: 0,
        inputCostPer1k: '0.6',
        outputCostPer1k: '12.0',
        capabilities: ['tts'],
        performance: {
          latencyMs: 1000,
          throughput: 200,
          quality: 0.85,
          reliability: 0.96,
        },
      },
      {
        id: 'openai:gpt-4o-transcribe',
        providerId: 'openai',
        name: 'gpt-4o-transcribe',
        displayName: 'GPT-4o Transcribe',
        contextWindow: 0,
        maxOutputTokens: 0,
        inputCostPer1k: '2.5',
        outputCostPer1k: '10.0',
        capabilities: ['speech_to_text'],
        performance: {
          latencyMs: 1500,
          throughput: 120,
          quality: 0.94,
          reliability: 0.98,
        },
      },
      {
        id: 'openai:gpt-4o-transcribe-diarize',
        providerId: 'openai',
        name: 'gpt-4o-transcribe-diarize',
        displayName: 'GPT-4o Transcribe Diarize',
        contextWindow: 0,
        maxOutputTokens: 0,
        inputCostPer1k: '2.5',
        outputCostPer1k: '10.0',
        capabilities: ['speech_to_text', 'diarization'],
        performance: {
          latencyMs: 1600,
          throughput: 115,
          quality: 0.945,
          reliability: 0.98,
        },
      },
      {
        id: 'openai:gpt-4o-mini-transcribe',
        providerId: 'openai',
        name: 'gpt-4o-mini-transcribe',
        displayName: 'GPT-4o Mini Transcribe',
        contextWindow: 0,
        maxOutputTokens: 0,
        inputCostPer1k: '1.25',
        outputCostPer1k: '5.0',
        capabilities: ['speech_to_text'],
        performance: {
          latencyMs: 1200,
          throughput: 150,
          quality: 0.89,
          reliability: 0.97,
        },
      },
      {
        id: 'openai:tts-1',
        providerId: 'openai',
        name: 'tts-1',
        displayName: 'TTS-1',
        contextWindow: 4096,
        maxOutputTokens: 0,
        inputCostPer1k: '15.0',
        outputCostPer1k: '0',
        capabilities: ['tts'],
        performance: {
          latencyMs: 800,
          throughput: 300,
          quality: 0.82,
          reliability: 0.95,
        },
      },
      {
        id: 'openai:tts-1-hd',
        providerId: 'openai',
        name: 'tts-1-hd',
        displayName: 'TTS-1 HD',
        contextWindow: 4096,
        maxOutputTokens: 0,
        inputCostPer1k: '30.0',
        outputCostPer1k: '0',
        capabilities: ['tts'],
        performance: {
          latencyMs: 1200,
          throughput: 200,
          quality: 0.88,
          reliability: 0.96,
        },
      },
      {
        id: 'openai:whisper-1',
        providerId: 'openai',
        name: 'whisper-1',
        displayName: 'Whisper 1',
        contextWindow: 0,
        maxOutputTokens: 0,
        inputCostPer1k: '0.006',
        outputCostPer1k: '0',
        capabilities: ['speech_to_text'],
        performance: {
          latencyMs: 1000,
          throughput: 100,
          quality: 0.85,
          reliability: 0.94,
        },
      },

      // Embeddings
      {
        id: 'openai:text-embedding-3-small',
        providerId: 'openai',
        name: 'text-embedding-3-small',
        displayName: 'Text Embedding 3 Small',
        contextWindow: 8192,
        maxOutputTokens: 0,
        inputCostPer1k: '0.02',
        outputCostPer1k: '0',
        capabilities: ['embeddings'],
        performance: {
          latencyMs: 200,
          throughput: 500,
          quality: 0.88,
          reliability: 0.99,
        },
      },
      {
        id: 'openai:text-embedding-3-large',
        providerId: 'openai',
        name: 'text-embedding-3-large',
        displayName: 'Text Embedding 3 Large',
        contextWindow: 8192,
        maxOutputTokens: 0,
        inputCostPer1k: '0.13',
        outputCostPer1k: '0',
        capabilities: ['embeddings'],
        performance: {
          latencyMs: 300,
          throughput: 300,
          quality: 0.92,
          reliability: 0.99,
        },
      },
      {
        id: 'openai:text-embedding-ada-002',
        providerId: 'openai',
        name: 'text-embedding-ada-002',
        displayName: 'Text Embedding Ada 002',
        contextWindow: 8192,
        maxOutputTokens: 0,
        inputCostPer1k: '0.1',
        outputCostPer1k: '0',
        capabilities: ['embeddings'],
        performance: {
          latencyMs: 400,
          throughput: 200,
          quality: 0.85,
          reliability: 0.98,
        },
      },

      // Imagens DALL-E
      {
        id: 'openai:dall-e-3',
        providerId: 'openai',
        name: 'dall-e-3',
        displayName: 'DALL-E 3',
        contextWindow: 0,
        maxOutputTokens: 0,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['image_generation'],
        performance: {
          latencyMs: 10000,
          throughput: 20,
          quality: 0.9,
          reliability: 0.95,
        },
      },
      {
        id: 'openai:dall-e-2',
        providerId: 'openai',
        name: 'dall-e-2',
        displayName: 'DALL-E 2',
        contextWindow: 0,
        maxOutputTokens: 0,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['image_generation'],
        performance: {
          latencyMs: 8000,
          throughput: 30,
          quality: 0.8,
          reliability: 0.93,
        },
      },

      // Legacy GPT-4 and GPT-3.5 Models
      {
        id: 'openai:chatgpt-4o-latest',
        providerId: 'openai',
        name: 'chatgpt-4o-latest',
        displayName: 'ChatGPT-4o Latest',
        contextWindow: 128000,
        maxOutputTokens: 16384,
        inputCostPer1k: '5.0',
        outputCostPer1k: '15.0',
        capabilities: ['chat', 'function_calling', 'vision', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 2200,
          throughput: 90,
          quality: 0.94,
          reliability: 0.98,
        },
      },
      {
        id: 'openai:gpt-4-turbo-2024-04-09',
        providerId: 'openai',
        name: 'gpt-4-turbo-2024-04-09',
        displayName: 'GPT-4 Turbo (2024-04-09)',
        contextWindow: 128000,
        maxOutputTokens: 4096,
        inputCostPer1k: '10.0',
        outputCostPer1k: '30.0',
        capabilities: ['chat', 'function_calling', 'vision', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 3000,
          throughput: 70,
          quality: 0.92,
          reliability: 0.97,
        },
      },
      {
        id: 'openai:gpt-4-0125-preview',
        providerId: 'openai',
        name: 'gpt-4-0125-preview',
        displayName: 'GPT-4 (0125 Preview)',
        contextWindow: 128000,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['chat', 'function_calling', 'vision', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 3500,
          throughput: 60,
          quality: 0.9,
          reliability: 0.95,
        },
      },
      {
        id: 'openai:gpt-4-1106-preview',
        providerId: 'openai',
        name: 'gpt-4-1106-preview',
        displayName: 'GPT-4 (1106 Preview)',
        contextWindow: 128000,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['chat', 'function_calling', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 3200,
          throughput: 65,
          quality: 0.895,
          reliability: 0.955,
        },
      },
      {
        id: 'openai:gpt-4-1106-vision-preview',
        providerId: 'openai',
        name: 'gpt-4-1106-vision-preview',
        displayName: 'GPT-4 Vision (1106 Preview)',
        contextWindow: 128000,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['chat', 'function_calling', 'vision', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 3400,
          throughput: 62,
          quality: 0.905,
          reliability: 0.96,
        },
      },
      {
        id: 'openai:gpt-4-0613',
        providerId: 'openai',
        name: 'gpt-4-0613',
        displayName: 'GPT-4 (0613)',
        contextWindow: 8192,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['chat', 'function_calling', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 4000,
          throughput: 50,
          quality: 0.88,
          reliability: 0.93,
        },
      },
      {
        id: 'openai:gpt-4-0314',
        providerId: 'openai',
        name: 'gpt-4-0314',
        displayName: 'GPT-4 (0314)',
        contextWindow: 8192,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['chat', 'function_calling', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 4200,
          throughput: 48,
          quality: 0.875,
          reliability: 0.92,
        },
      },
      {
        id: 'openai:gpt-4-32k',
        providerId: 'openai',
        name: 'gpt-4-32k',
        displayName: 'GPT-4 32K',
        contextWindow: 32768,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['chat', 'function_calling', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 4500,
          throughput: 45,
          quality: 0.885,
          reliability: 0.935,
        },
      },
      {
        id: 'openai:gpt-3.5-turbo',
        providerId: 'openai',
        name: 'gpt-3.5-turbo',
        displayName: 'GPT-3.5 Turbo',
        contextWindow: 16384,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['chat', 'function_calling', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 2000,
          throughput: 100,
          quality: 0.8,
          reliability: 0.95,
        },
      },
      {
        id: 'openai:gpt-3.5-turbo-0125',
        providerId: 'openai',
        name: 'gpt-3.5-turbo-0125',
        displayName: 'GPT-3.5 Turbo (0125)',
        contextWindow: 16384,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['chat', 'function_calling', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 1900,
          throughput: 105,
          quality: 0.805,
          reliability: 0.955,
        },
      },
      {
        id: 'openai:gpt-3.5-turbo-1106',
        providerId: 'openai',
        name: 'gpt-3.5-turbo-1106',
        displayName: 'GPT-3.5 Turbo (1106)',
        contextWindow: 16384,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['chat', 'function_calling', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 1950,
          throughput: 102,
          quality: 0.802,
          reliability: 0.952,
        },
      },
      {
        id: 'openai:gpt-3.5-turbo-0613',
        providerId: 'openai',
        name: 'gpt-3.5-turbo-0613',
        displayName: 'GPT-3.5 Turbo (0613)',
        contextWindow: 4096,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['chat', 'function_calling', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 1800,
          throughput: 110,
          quality: 0.795,
          reliability: 0.945,
        },
      },
      {
        id: 'openai:gpt-3.5-turbo-0301',
        providerId: 'openai',
        name: 'gpt-3.5-turbo-0301',
        displayName: 'GPT-3.5 Turbo (0301)',
        contextWindow: 4096,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['chat', 'function_calling', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 1850,
          throughput: 108,
          quality: 0.79,
          reliability: 0.94,
        },
      },
      {
        id: 'openai:gpt-3.5-turbo-16k-0613',
        providerId: 'openai',
        name: 'gpt-3.5-turbo-16k-0613',
        displayName: 'GPT-3.5 Turbo 16K (0613)',
        contextWindow: 16384,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['chat', 'function_calling', 'streaming', 'json_mode'],
        performance: {
          latencyMs: 2200,
          throughput: 90,
          quality: 0.798,
          reliability: 0.948,
        },
      },
      {
        id: 'openai:gpt-3.5-turbo-instruct',
        providerId: 'openai',
        name: 'gpt-3.5-turbo-instruct',
        displayName: 'GPT-3.5 Turbo Instruct',
        contextWindow: 4096,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['completions'],
        performance: {
          latencyMs: 1500,
          throughput: 120,
          quality: 0.75,
          reliability: 0.92,
        },
      },

      // Base models (legacy)
      {
        id: 'openai:davinci-002',
        providerId: 'openai',
        name: 'davinci-002',
        displayName: 'Davinci 002',
        contextWindow: 16384,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['completions'],
        performance: {
          latencyMs: 3000,
          throughput: 60,
          quality: 0.7,
          reliability: 0.88,
        },
      },
      {
        id: 'openai:babbage-002',
        providerId: 'openai',
        name: 'babbage-002',
        displayName: 'Babbage 002',
        contextWindow: 16384,
        maxOutputTokens: 4096,
        inputCostPer1k: '0',
        outputCostPer1k: '0',
        capabilities: ['completions'],
        performance: {
          latencyMs: 2500,
          throughput: 80,
          quality: 0.65,
          reliability: 0.85,
        },
      },
      {
        id: 'anthropic:claude-3.7-sonnet',
        providerId: 'anthropic',
        name: 'claude-3.7-sonnet',
        displayName: 'Claude 3.7 Sonnet',
        contextWindow: 200000,
        maxOutputTokens: 8192,
        inputCostPer1k: '0.004',
        outputCostPer1k: '0.02',
        capabilities: ['chat', 'function_calling', 'streaming', 'json_mode', 'vision', 'reasoning'],
        performance: {
          latencyMs: 1900,
          throughput: 100,
          quality: 0.98,
          reliability: 0.99,
        },
      },
      {
        id: 'google:gemini-1.5-pro',
        providerId: 'google',
        name: 'gemini-1.5-pro',
        displayName: 'Gemini 1.5 Pro',
        contextWindow: 1000000,
        maxOutputTokens: 8192,
        inputCostPer1k: '0.00125',
        outputCostPer1k: '0.005',
        capabilities: ['chat', 'function_calling', 'streaming', 'vision', 'json_mode'],
        performance: {
          latencyMs: 2100,
          throughput: 85,
          quality: 0.95,
          reliability: 0.98,
        },
      },
      {
        id: 'google:gemini-1.5-flash',
        providerId: 'google',
        name: 'gemini-1.5-flash',
        displayName: 'Gemini 1.5 Flash',
        contextWindow: 1000000,
        maxOutputTokens: 8192,
        inputCostPer1k: '0.000075',
        outputCostPer1k: '0.0003',
        capabilities: ['chat', 'function_calling', 'streaming', 'vision', 'json_mode'],
        performance: {
          latencyMs: 1200,
          throughput: 140,
          quality: 0.9,
          reliability: 0.98,
        },
      },
    ];

    for (const model of modelsToSeed) {
      const seedTimestamp = new Date().toISOString();
      const performanceJson = model.performance as Prisma.JsonObject;
      const metadataJson: Prisma.JsonObject = {
        seededAt: seedTimestamp,
        source: 'cli-live-tests',
      };
      const healthMetadata: Prisma.JsonObject = {
        seededAt: seedTimestamp,
      };

      const upsertedModel = await prisma.model.upsert({
        where: {
          providerId_name: {
            providerId: model.providerId,
            name: model.name,
          },
        },
        update: {
          id: model.id,
          providerId: model.providerId,
          name: model.name,
          displayName: model.displayName,
          contextWindow: model.contextWindow,
          maxOutputTokens: model.maxOutputTokens,
          inputCostPer1k: new Prisma.Decimal(model.inputCostPer1k),
          outputCostPer1k: new Prisma.Decimal(model.outputCostPer1k),
          capabilities: model.capabilities,
          performance: performanceJson,
          status: 'active',
          metadata: metadataJson,
          lastSyncedAt: new Date(),
        },
        create: {
          uid: computeModelUid(model.providerId, model.id),
          id: model.id,
          providerId: model.providerId,
          name: model.name,
          displayName: model.displayName,
          contextWindow: model.contextWindow,
          maxOutputTokens: model.maxOutputTokens,
          inputCostPer1k: new Prisma.Decimal(model.inputCostPer1k),
          outputCostPer1k: new Prisma.Decimal(model.outputCostPer1k),
          capabilities: model.capabilities,
          performance: performanceJson,
          status: 'active',
          metadata: metadataJson,
          lastSyncedAt: new Date(),
        },
      });

      await prisma.modelHealth.upsert({
        where: { modelId: upsertedModel.id },
        update: {
          modelUid: upsertedModel.uid,
          status: 'healthy',
          latencyMs: (model.performance as { latencyMs?: number }).latencyMs ?? null,
          availability: (model.performance as { reliability?: number }).reliability ?? 0.99,
          loadFactor: (model.performance as { throughput?: number }).throughput ?? 100,
          errorRate: 0,
          metadata: healthMetadata,
        },
        create: {
          modelId: upsertedModel.id,
          modelUid: upsertedModel.uid,
          status: 'healthy',
          latencyMs: (model.performance as { latencyMs?: number }).latencyMs ?? null,
          availability: (model.performance as { reliability?: number }).reliability ?? 0.99,
          loadFactor: (model.performance as { throughput?: number }).throughput ?? 100,
          errorRate: 0,
          metadata: healthMetadata,
        },
      });
    }

    logger.info(
      {
        organizationId: organization.id,
        ownerUserId: ownerUser.id,
        ownerEmail: ownerUser.email,
        providersSeeded: providersToSeed.length,
        modelsSeeded: modelsToSeed.length,
      },
      'Database seed completed successfully'
    );
  } catch (error: unknown) {
    const errorDetails = error instanceof Error
      ? { message: error.message, stack: error.stack, name: error.name }
      : { message: String(error) };
    logger.error(
      {
        error: errorDetails,
      },
      'Seed routine failed'
    );
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

if (require.main === module) {
  seedDatabase().catch((error) => {
    logger.fatal({ error: serializeError(error) }, 'Failed to seed database');
    process.exit(1);
  });
}
