// Copyright (C) 2026 Ailin One, Inc.
//
// This file is part of Collective Intelligence Engine (ci).
// Licensed under the GNU Affero General Public License v3.0 or later.
// See LICENSE in the repository root, or <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
// Source: https://github.com/ailinone/collective-intelligence

/**
 * Runtime Matrix Cardinality Guard
 *
 * The "Phase 1" of the SOTA Full Dynamic Provider Catalog Closure plan
 * produces a single source-of-truth CSV at
 * `api/docs/provider-runtime-matrix.csv` that joins the catalog with
 * runtime evidence (DB counts, GCP secret presence, plugin boot status,
 * fetcher existence, etc.). Phases 2–9 consume this matrix.
 *
 * The CSV is hand-generated by `api/scripts/_phase1-matrix.cjs` from
 * the canonical catalog plus operator-captured snapshots in `/tmp/`.
 * That means the CSV can drift out of sync with the catalog if
 * someone adds a new provider entry without re-running the script.
 *
 * This test catches that drift early: the CSV row count (excluding
 * the header) must equal the catalog row count. If it doesn't, the
 * matrix is stale and downstream phases (failure diagnosis, fetcher
 * decisions, drop list) would operate on incorrect data.
 *
 * Re-generate via:
 *   node api/scripts/_phase1-matrix.cjs
 *
 * The script is intentionally a `.cjs` Node script (no TypeScript
 * compile step needed) so the operator can run it from a clean
 * checkout without `pnpm install`.
 */

import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { PROVIDER_CATALOG } from '../providers.catalog';

describe('Phase 1 — runtime matrix cardinality', () => {
  const csvPath = join(__dirname, '..', '..', '..', '..', 'docs', 'provider-runtime-matrix.csv');

  it('CSV exists at the canonical location', () => {
    expect(existsSync(csvPath)).toBe(true);
  });

  it('CSV row count equals catalog row count (no drift)', () => {
    const csv = readFileSync(csvPath, 'utf-8');
    // Count lines, excluding header AND any trailing blank line.
    const lines = csv.split('\n').filter((l) => l.trim().length > 0);
    const dataRows = lines.length - 1; // minus header
    expect(dataRows).toBe(PROVIDER_CATALOG.length);
  });

  it('every catalog providerId appears as a CSV row', () => {
    const csv = readFileSync(csvPath, 'utf-8');
    const lines = csv.split('\n').filter((l) => l.trim().length > 0);
    // First column is providerId. Skip header.
    const csvProviderIds = new Set(
      lines.slice(1).map((line) => line.split(',')[0]),
    );
    const catalogProviderIds = PROVIDER_CATALOG.map((e) => e.providerId);

    const missing = catalogProviderIds.filter((id) => !csvProviderIds.has(id));
    expect(missing).toEqual([]);
  });

  it('CSV header contains the canonical 22 columns', () => {
    const csv = readFileSync(csvPath, 'utf-8');
    const header = csv.split('\n')[0];
    const columns = header.split(',');
    // Spot-check key columns; full list is in the script.
    expect(columns).toContain('providerId');
    expect(columns).toContain('integrationMode');
    expect(columns).toContain('hasStaticModels');
    expect(columns).toContain('secretWiredAllTables');
    expect(columns).toContain('secretExistsInGCP');
    expect(columns).toContain('pluginStatus');
    expect(columns).toContain('modelsInDb');
    expect(columns).toContain('status');
    expect(columns).toContain('decision');
  });
});
