# Copyright (C) 2026 Ailin One, Inc.
#
# This file is part of Collective Intelligence Engine (ci).
# Licensed under the GNU Affero General Public License v3.0 or later.
# See LICENSE in the repository root, or <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later
# Source: https://github.com/ailinone/collective-intelligence

name: deploy-api-on-push
description: Deploy API to Cloud Run on push to main
github:
  owner: YOUR_GITHUB_ORG
  name: YOUR_REPO_NAME
  push:
    branch: ^main$
filename: api/cloudbuild.yaml
includedFiles:
  - api/**
substitutions:
  _COMMIT_SHA: SHORT_SHA

